const MDP = (() => {
  const WHATSAPP_NUMBER = '2348000000000'; // Replace with M.D Gadgets' business WhatsApp number.
  const PRODUCTS_KEY = 'mdGadgetsProducts';
  const CART_KEY = 'mdGadgetsCart';
  const seedProducts = [
    {id:1,name:'iPhone 14 Plus',brand:'Apple',category:'Phones',price:550000,oldPrice:600000,storage:'128GB',ram:'6GB',condition:'UK Used',description:'Clean UK used iPhone 14 Plus.\n\nBattery health: 89%\nFace ID: Working\nTrue Tone: Working\nCamera: Working perfectly\nNetwork: Unlocked\nCondition: Very clean.\n\nAvailable for negotiation.',image:'assets/images/phones/iphone-14-plus.jpg',gallery:[],status:'HOT-DEAL',stock:true,dateAdded:'2026-09-28'},
    {id:2,name:'Galaxy S23 Ultra',brand:'Samsung',category:'Phones',price:690000,oldPrice:735000,storage:'256GB',ram:'12GB',condition:'Foreign Used',description:'Premium Samsung Galaxy S23 Ultra in excellent condition. Factory unlocked with a vivid display, powerful cameras and smooth performance.',image:'assets/images/phones/galaxy-s23.jpg',gallery:[],status:'SELL',stock:true,dateAdded:'2026-09-26'},
    {id:3,name:'MacBook Air M2',brand:'Apple',category:'Laptops',price:870000,oldPrice:930000,storage:'256GB SSD',ram:'8GB',condition:'UK Used',description:'Clean MacBook Air M2 with a crisp Retina display, reliable battery and compact design. Perfect for work, school and creative tasks.',image:'assets/images/laptops/macbook-air.jpg',gallery:[],status:'HOT-DEAL',stock:true,dateAdded:'2026-09-24'},
    {id:4,name:'Dell XPS 13',brand:'Dell',category:'Laptops',price:610000,oldPrice:null,storage:'512GB SSD',ram:'16GB',condition:'Foreign Used',description:'Premium Dell XPS 13, professionally inspected and ready for everyday productivity.',image:'assets/images/laptops/dell-xps.jpg',gallery:[],status:'SELL',stock:true,dateAdded:'2026-09-20'},
    {id:5,name:'PlayStation 5 Slim',brand:'Sony',category:'PlayStation',price:780000,oldPrice:825000,storage:'1TB',ram:'16GB',condition:'Brand New',description:'Sony PlayStation 5 Slim console with immersive gaming performance. Comes complete and ready for your next game night.',image:'assets/images/playstation/ps5.jpg',gallery:[],status:'HOT-DEAL',stock:true,dateAdded:'2026-09-29'},
    {id:6,name:'AirPods Pro (2nd Gen)',brand:'Apple',category:'Accessories',price:185000,oldPrice:null,storage:'USB-C Case',ram:'—',condition:'Brand New',description:'Original AirPods Pro with active noise cancellation, comfortable fit and USB-C charging case.',image:'assets/images/accessories/airpods-pro.jpg',gallery:[],status:'SELL',stock:true,dateAdded:'2026-09-18'},
    {id:7,name:'iPhone 13 Pro',brand:'Apple',category:'Phones',price:495000,oldPrice:null,storage:'256GB',ram:'6GB',condition:'UK Used',description:'A very clean iPhone 13 Pro with excellent camera performance, Face ID and unlocked network.',image:'assets/images/phones/iphone-13-pro.jpg',gallery:[],status:'SOLD',stock:false,dateAdded:'2026-09-15'},
    {id:8,name:'HP EliteBook 840 G8',brand:'HP',category:'Laptops',price:445000,oldPrice:null,storage:'512GB SSD',ram:'16GB',condition:'UK Used',description:'Reliable HP EliteBook for business, remote work and study. Fully tested and neatly presented.',image:'assets/images/laptops/hp-elitebook.jpg',gallery:[],status:'SELL',stock:true,dateAdded:'2026-09-12'}
  ];
  const money = value => `₦${Number(value || 0).toLocaleString('en-NG')}`;
  const getProducts = () => JSON.parse(localStorage.getItem(PRODUCTS_KEY)) || seedProducts;
  const saveProducts = products => localStorage.setItem(PRODUCTS_KEY, JSON.stringify(products));
  const getCart = () => JSON.parse(localStorage.getItem(CART_KEY)) || [];
  const saveCart = cart => { localStorage.setItem(CART_KEY, JSON.stringify(cart)); updateCartCount(); };
  const getProduct = id => getProducts().find(product => product.id === Number(id));
  const isAvailable = product => product && product.status !== 'SOLD' && product.stock;
  const updateCartCount = () => document.querySelectorAll('[data-cart-count]').forEach(node => { node.textContent = getCart().reduce((sum, item) => sum + item.quantity, 0); });
  const addToCart = id => { const product = getProduct(id); if (!isAvailable(product)) return; const cart = getCart(); const found = cart.find(item => item.id === product.id); found ? found.quantity++ : cart.push({id:product.id, quantity:1}); saveCart(cart); showToast(`${product.name} added to cart`); };
  const setNegotiation = ids => { localStorage.setItem('mdGadgetsNegotiation', JSON.stringify(ids.map(Number))); window.location.href = 'negotiate.html'; };
  const whatsapp = message => window.open(`https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(message)}`, '_blank', 'noopener');
  const statusClass = status => status.toLowerCase().replace('-', '');
  const productCard = product => { const available = isAvailable(product); return `<article class="product-card"><div class="product-image"><img src="${product.image}" alt="${product.name}" onerror="this.src='https://images.unsplash.com/photo-1592750475338-74b7b21085ab?auto=format&fit=crop&w=900&q=80'"><span class="status ${statusClass(product.status)}">${product.status}</span></div><div class="product-copy"><p class="eyebrow">${product.brand} · ${product.category}</p><h3>${product.name}</h3><p class="spec">${product.storage} · ${product.ram} · ${product.condition}</p><div class="prices"><strong>${money(product.price)}</strong>${product.oldPrice ? `<del>${money(product.oldPrice)}</del>` : ''}</div><div class="card-actions"><a class="btn btn-outline" href="product.html?id=${product.id}">View details</a><button class="btn btn-quiet" ${available ? `data-negotiate="${product.id}"` : 'disabled'}>Negotiate</button><button class="btn btn-gold" ${available ? `data-add-cart="${product.id}"` : 'disabled'}>${available ? 'Add to cart' : 'Sold out'}</button></div></div></article>`; };
  const bindProductActions = () => { document.querySelectorAll('[data-add-cart]').forEach(button => button.onclick = () => addToCart(button.dataset.addCart)); document.querySelectorAll('[data-negotiate]').forEach(button => button.onclick = () => setNegotiation([button.dataset.negotiate])); };
  const showToast = message => { let toast = document.querySelector('.toast'); if (!toast) { toast = document.createElement('div'); toast.className = 'toast'; document.body.append(toast); } toast.textContent = message; toast.classList.add('show'); setTimeout(() => toast.classList.remove('show'), 2600); };
  return {WHATSAPP_NUMBER, money, getProducts, saveProducts, getProduct, getCart, saveCart, isAvailable, updateCartCount, addToCart, setNegotiation, whatsapp, productCard, bindProductActions, showToast};
})();
